### PR TITLE
fix: k3s yaml link so tutorial works and updated the image with new yaml url

### PR DESCRIPTION
**Pull request by waltribeiro**
In preparation for my KCNA, I ran through Equinix's K3s and K8s tutorials. This React app was a big help, but it kept giving me a 404. So I updated the YAML and image. 

### Steps to Reproduce
1) Launch server with this _user data_:
```
#cloud-config

runcmd:
  - curl -sfL https://get.k3s.io | sh -
  - sleep 20
  - kubectl apply -f https://raw.githubusercontent.com/stevemar/react-wordle/main/reactle-kube-deploy.yaml
```
 
2) Received [an error](https://raw.githubusercontent.com/stevemar/react-wordle/main/reactle-kube-deploy.yaml)

3) Replace with this _user data_:
```
#cloud-config

runcmd:
  - curl -sfL https://get.k3s.io | sh -
  - sleep 20
  - kubectl apply -f https://raw.githubusercontent.com/stevemar/metal-code-snippets/main/yaml/reactle.yaml
  ```
4) Received [working](https://raw.githubusercontent.com/stevemar/metal-code-snippets/main/yaml/reactle.yaml)

5) Go to `http://<localhost>:31000` and confirmed Reactle / Wordle app works.

### CODE REVIEW

**Review by stevemar — APPROVED** [review]

**Comment by stevemar** [comment]
fixes it not working, so lgtm. but in general, we should move away from the wordle clones to something like [wordpress](https://github.com/stevemar/metal-code-snippets/blob/main/yaml/wordpress.yaml).

**Comment by waltribeiro** [comment]
Should I create a new workshop for Wordpress using `https://raw.githubusercontent.com/stevemar/metal-code-snippets/main/yaml/wordpress.yaml` and then update the instructions for `<ip>:30001` ?

**Comment by stevemar** [comment]
@waltribeiro i would update this workshop with that link (provided it works!)

**Comment by waltribeiro** [comment]
OK. [Here you go!](https://github.com/equinix-labs/intro-to-metal-workshop/pull/6)

**Pull request merged**
